//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecentLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ABIs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ABIs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecentLib.ABIs", typeof(ABIs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;inputs&quot;: [],
        ///		&quot;payable&quot;: false,
        ///		&quot;stateMutability&quot;: &quot;nonpayable&quot;,
        ///		&quot;type&quot;: &quot;constructor&quot;
        ///	},
        ///	{
        ///		&quot;anonymous&quot;: false,
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;indexed&quot;: false,
        ///				&quot;internalType&quot;: &quot;bytes32&quot;,
        ///				&quot;name&quot;: &quot;id&quot;,
        ///				&quot;type&quot;: &quot;bytes32&quot;
        ///			},
        ///			{
        ///				&quot;indexed&quot;: true,
        ///				&quot;internalType&quot;: &quot;address&quot;,
        ///				&quot;name&quot;: &quot;sender&quot;,
        ///				&quot;type&quot;: &quot;address&quot;
        ///			},
        ///			{
        ///				&quot;indexed&quot;: false,
        ///				&quot;internalType&quot;: &quot;uint256&quot;,
        ///				&quot;name&quot;: &quot;amount&quot;,
        ///				&quot;type&quot;: &quot;uint256&quot;
        ///			}
        ///		],
        ///		&quot;name&quot;: &quot;Channe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaymentChannelsABI {
            get {
                return ResourceManager.GetString("PaymentChannelsABI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;inputs&quot;: [],
        ///		&quot;payable&quot;: false,
        ///		&quot;stateMutability&quot;: &quot;nonpayable&quot;,
        ///		&quot;type&quot;: &quot;constructor&quot;
        ///	},
        ///	{
        ///		&quot;constant&quot;: true,
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;internalType&quot;: &quot;address&quot;,
        ///				&quot;name&quot;: &quot;&quot;,
        ///				&quot;type&quot;: &quot;address&quot;
        ///			},
        ///			{
        ///				&quot;internalType&quot;: &quot;address&quot;,
        ///				&quot;name&quot;: &quot;&quot;,
        ///				&quot;type&quot;: &quot;address&quot;
        ///			}
        ///		],
        ///		&quot;name&quot;: &quot;consumerVotes&quot;,
        ///		&quot;outputs&quot;: [
        ///			{
        ///				&quot;internalType&quot;: &quot;uint256&quot;,
        ///				&quot;name&quot;: &quot;&quot;,
        ///				&quot;type&quot;: &quot;uint256&quot;
        ///			}
        ///		],
        ///		&quot;payable&quot;: false,
        ///		&quot;stateMutability&quot;: &quot;view&quot;,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfileABI {
            get {
                return ResourceManager.GetString("ProfileABI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;internalType&quot;: &quot;address[]&quot;,
        ///				&quot;name&quot;: &quot;initial&quot;,
        ///				&quot;type&quot;: &quot;address[]&quot;
        ///			}
        ///		],
        ///		&quot;payable&quot;: false,
        ///		&quot;stateMutability&quot;: &quot;nonpayable&quot;,
        ///		&quot;type&quot;: &quot;constructor&quot;
        ///	},
        ///	{
        ///		&quot;anonymous&quot;: false,
        ///		&quot;inputs&quot;: [
        ///			{
        ///				&quot;indexed&quot;: false,
        ///				&quot;internalType&quot;: &quot;address[]&quot;,
        ///				&quot;name&quot;: &quot;currentSet&quot;,
        ///				&quot;type&quot;: &quot;address[]&quot;
        ///			}
        ///		],
        ///		&quot;name&quot;: &quot;ChangeFinalized&quot;,
        ///		&quot;type&quot;: &quot;event&quot;
        ///	},
        ///	{
        ///		&quot;constant&quot;: false,
        ///		&quot;inputs&quot;: [],
        ///		&quot;name&quot;: &quot;finalizeChange&quot;,
        ///		&quot;outp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidatorsABI {
            get {
                return ResourceManager.GetString("ValidatorsABI", resourceCulture);
            }
        }
    }
}
